# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirm_la', '0002_auto_20170713_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
    ]
